# Setup
title:               Ahamed's Blog
tagline:             'Technology, IT Practices , Trials & Errors'
description: 'Personal Views & Rant on Technology & Practices,  with Logic'
url:                 https://ahamedm.github.io
baseurl:             ''
paginate:            4
permalink:           pretty

# About/contact
author:
  name:              Ahamed Mustafa
  url:               https://ahamedm.github.io
  email:             ahamedm@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
